#!/bin/bash

# TODO:
# - Fix bug where at failing importing tar image, after rebuilding image is saved without version (:latest, :nr)
usage()
{
cat << EOF

usage: $(basename $0) options INSTANCE

This script handles your CoreOS (coreos.com) instances with Vagrant (vagrantup.com)

OPTIONS:
	-h (help)           Show this message
	-r (reload)         Reload the instance
	-R (rebuild)        Rebuild the instance
	-c (command)        -c=command Pass a command to the coreos instance
	-p (provision)      Provision the instance
	-d (destroy)        Kill and destroy instance
	-s (status)         See Vagrants global status
	-v (debug)			Vagrant debug mode

EOF
}

count=0
while getopts "hc:rRpdsv" OPTION
do
	case "$OPTION" in
		h|help)
			usage
			exit 1
			;;
		c|command)
			COMMAND="$OPTARG"
			;;
		r|reload)
			RELOAD=1
			;;
		R|rebuild)
			REBUILD=1
			;;
		p|provision)
			PROVISION=1
			;;
		d|destroy)
			DESTROY=1
			;;
		s|status)
			STATUS=1
			;;
		v|verbose|debug)
			DEBUG="--debug"
			;;
		?)
			usage
			exit
		;;
	esac
	count=`expr $count + 1`
	if [ "$OPTARG" ]
	then
		count=`expr $count + 1`
	fi
done
shift $count

black="\e[0;30m"
red="\e[0;31m"
green="\e[0;32m"
orange="\e[0;33m"
blue="\e[0;34m"
purple="\e[0;35m"
turquase="\e[0;36m"
NC="\e[0m"

function info ()
{
	printf "$turquase"
	echo "$1"
	printf "$NC"
}

function success ()
{
	printf "$green"
	echo "$1"
	printf "$NC"
}

function warning ()
{
    printf "$orange"
    echo "$1"
    printf "$NC"
}

function error ()
{
	printf "$red"
	echo "$1"
	printf "$NC"
}

INSTANCE="$1"

if [ "$(which vagrant)" == "" ]
then
	error "Vagrant could not be found."
	exit
fi

env="$(cat "$WORKSPACE/env.json")"
function get_json()
{
    echo $1 | sed -e 's/^[{}]*//g' | awk -F=':' -v RS=',' "\$1~/\"$2\"/ {print}" | sed -e "s/\"$2\"://" | tr -d "\n\t" | sed -e 's/\\"/"/g' | sed -e 's/\\\\/\\/g' | sed -e 's/^[ \t]*//g' | sed -e 's/^"//'  -e 's/"$//'
}

provider="$(get_json "$env" 'provider')"
export VAGRANT_DEFAULT_PROVIDER="${provider//-/_}"
if [ "$VAGRANT_HOME" == "" ]
then
	vagrant_home="$WORKSPACE/.vagrant.d"
	if [ ! -d "$HOME/.vagrant.d" ] && [ ! -d "$vagrant_home" ]
	then
		mkdir "$vagrant_home"
	fi
	if [ ! -d "$vagrant_home" ]
	then
		vagrant_home="$HOME/.vagrant.d"
	fi
	export VAGRANT_HOME="$vagrant_home"
fi

while [ "$(cat "$WORKSPACE/config/git.json")" == "$(cat "$WORKSPACE/workspace-image/config-boilerplate/git.json")" ]
do
	info "Please enter the path to your Git config file or edit ${WORKSPACE/$HOME/~}/config/git.json manually and hit [enter]."
    read git_config_file
    if [ "$git_config_file" != "" ]
	then
		if [ "${git_config_file:$(expr ${#git_config_file} - 5):5}" != '.json' ]
		then
			git_config_file="$git_config_file/git.json"
		fi
		
		scp "$git_config_file" "$WORKSPACE/config/git.json"

		if [ "$(cat "$WORKSPACE/config/git.json")" == "$(cat "$WORKSPACE/workspace-image/config-boilerplate/git.json")" ]
		then
			warning "No Git config file found."
		else
			success "Git config file found!"
		fi
	elif [ "$(cat "$WORKSPACE/config/git.json")" == "$(cat "$WORKSPACE/workspace-image/config-boilerplate/git.json")" ]
	then
		warning "No changes detected in git.json"
	fi
done

if [ "$provider" == "vmware-fusion" ] && [ ! -f "$VAGRANT_HOME/license-vagrant-vmware-fusion.lic" ]
then
	while [ ! -f "$WORKSPACE/config/"*.lic ]
	do
		info "Please enter the path to your Vagrant VMWare Fusion License file or place it manually in your ${WORKSPACE/$HOME/~}/config directory and hit [enter]."
		read vagrant_vmware_fusion_license
		if [ "$vagrant_vmware_fusion_license" == "" ]
		then
			exit
		fi
		
		if [ "${vagrant_vmware_fusion_license:$(expr ${#vagrant_vmware_fusion_license} - 4):4}" != '.lic' ]
		then
			vagrant_vmware_fusion_license="$vagrant_vmware_fusion_license/"*.lic
		fi
		
		scp "$vagrant_vmware_fusion_license" "$WORKSPACE/config/"

		if [ ! -f "$WORKSPACE/config/"*.lic ]
		then
			warning "No license file found."
		fi
	done
	success "License file found!"
	vagrant plugin install vagrant-vmware-fusion || exit
	vagrant plugin license vagrant-vmware-fusion "$(ls "$WORKSPACE/config/"*.lic | head -1)"

	# Check if VMWare has ran a first time before
	if [ ! -d "$HOME/Library/Application Support/VMWare Fusion" ]
	then
		if [ -d "$HOME/Applications/VMWare Fusion.app" ]
		then
			vmware_app="$HOME/Applications/VMWare Fusion.app"
		elif [ -d "/Applications/VMWare Fusion.app" ]
		then
			vmware_app="/Applications/VMWare Fusion.app"
		else
			error "There was no VMWare Fusion.app found on your system"
			error "Install VirtualBox or VMWare Fusion first"
			exit
		fi
		
		open "$vmware_app"
		info "Please run 'workspace' again if the VMWare Fusion is activated"
		exit
	fi
elif [ "$provider" == "virtualbox" ] && [ -f "$WORKSPACE/.system/"*.vbox-extpack ]
then
	if [ ! -f "$WORKSPACE/.system/extpack-installed" ]
	then
		open "$WORKSPACE/.system/"*.vbox-extpack
		info "Please run 'workspace' again if the Extension Pack has been installed"
		touch "$WORKSPACE/.system/extpack-installed"
		exit
	else
		rm -f "$WORKSPACE/.system/"*.vbox-extpack
		rm -f "$WORKSPACE/.system/extpack-installed"
	fi
fi

if [ $STATUS ]
then
	vagrant global-status
	exit
fi

if [ ! "$INSTANCE" ]
then
	INSTANCE=1
fi

INSTANCE="$(printf "%0*d\n" 2 ${INSTANCE:-1})"

running_file="$WORKSPACE/.system/coreos-$INSTANCE-running"

if [ $REBUILD ] || [ $DESTROY ]
then
	info "Destroying coreos-$INSTANCE..."
	vagrant destroy -f "coreos-$INSTANCE" 2>/dev/null
	
	if [ $DESTROY ]
	then
		vagrant global-status
		exit
	fi
fi

function vagrant_ssh()
{
	if [ "${COMMAND:0:9}" == "workspace" ]
	then
		info "Logging into workspace on coreos-$INSTANCE..."
		vagrant ssh --command "$COMMAND" "coreos-$INSTANCE"
	elif [ "$COMMAND" != "" ]
	then
		info "Running your command on coreos-$INSTANCE..."
		vagrant ssh --command "$COMMAND" "coreos-$INSTANCE"
	else
		info "Logging into coreos-$INSTANCE..."
		vagrant ssh "coreos-$INSTANCE"
	fi
}

if [ ! $RELOAD ] && [ -f "$running_file" ]
then
	vagrant_ssh
	info "... checking status"
	status="$(vagrant status coreos-$INSTANCE 2>/dev/null)"
	if [ "${status/not running/}" != "$status" ]
	then
		rm "$running_file"
		./coreos
	fi
	exit
fi

info "Looking for status coreos-$INSTANCE..."
status="$(vagrant status coreos-$INSTANCE 2>/dev/null)"
if [ "${status/not running/}" != "$status" ]
then
	info "Resuming coreos-$INSTANCE..."
	vagrant up "coreos-$INSTANCE" $DEBUG
elif [ "${status/not created/}" != "$status" ]
then
	info "Creating coreos-$INSTANCE..."
	vagrant up "coreos-$INSTANCE" $DEBUG
else
	if [ "$INSTANCE" == "01" ] && [ "$(vagrant ssh --command "ls -A /workspace" "coreos-$INSTANCE")" == "" ]
	then
		RELOAD=1
	fi
	if [ $RELOAD ]
	then
		info "Reloading coreos-$INSTANCE"
		if [ $PROVISION ]
		then
			vagrant reload "coreos-$INSTANCE"
		else
			vagrant reload --provision "coreos-$INSTANCE"
		fi
	else
		info "Already running coreos-$INSTANCE"
		if [ $PROVISION ]
		then
			info "Provisioning coreos-$INSTANCE..."
			vagrant provision "coreos-$INSTANCE"
		fi
	fi
fi

status="$(vagrant status coreos-$INSTANCE 2>/dev/null)"
if [ "${status/not running/}" == "$status" ]
then
	touch "$running_file"
	vagrant_ssh
fi