#!/bin/bash

# TODO:
# - Fix bug where at failing importing tar image, after rebuilding image is saved without version (:latest, :nr)
usage()
{
cat << EOF

usage: $(basename $0) options INSTANCE

This script handles your CoreOS (coreos.com) instances with Vagrant (vagrantup.com)

OPTIONS:
	-h (help)           Show this message
	-r (reload)         Reload the instance
	-R (rebuild)        Rebuild the instance
	-c (command)        -c=command Pass a command to the coreos instance
	-p (provision)      Provision the instance
	-d (destroy)        Kill and destroy instance
	-s (status)         See Vagrants global status
	-v (debug)			Vagrant debug mode
	-f (function)		Run a specific function from this executable
EOF
}

count=0
while getopts "hc:rRpdsvf:" OPTION
do
	case "$OPTION" in
		h|help)
			usage
			exit 1
			;;
		c|command)
			COMMAND="$OPTARG"
			;;
		r|reload)
			RELOAD=1
			;;
		R|rebuild)
			REBUILD=1
			;;
		p|provision)
			PROVISION=1
			;;
		d|destroy)
			DESTROY=1
			;;
		s|status)
			STATUS=1
			;;
		v|verbose|debug)
			DEBUG="--debug"
			;;
		f|function)
			FUNCTION="$OPTARG"
			;;
		?)
			usage
			exit
		;;
	esac
	count=`expr $count + 1`
	if [ "$OPTARG" ]
	then
		count=`expr $count + 1`
	fi
done
shift $count

black="\e[0;30m"
red="\e[0;31m"
green="\e[0;32m"
orange="\e[0;33m"
blue="\e[0;34m"
purple="\e[0;35m"
turquase="\e[0;36m"
NC="\e[0m"

function info ()
{
	printf "$turquase"
	echo "$1"
	printf "$NC"
}

function success ()
{
	printf "$green"
	echo "$1"
	printf "$NC"
}

function warning ()
{
    printf "$orange"
    echo "$1"
    printf "$NC"
}

function error ()
{
	printf "$red"
	echo "$1"
	printf "$NC"
}

function fetch_ip ()
{
	./coreos -c "ifconfig | grep -Eo 'inet (addr:)?([0-9]*\.){3}[0-9]*' | grep -Eo '([0-9]*\.){3}[0-9]*' | grep -v '127.0.0.1' | tail -n 1 > /workspace/.system/$1-ip"
    ip="$(cat ./.system/$1-ip)"
    #  | sudo tee -a /etc/hosts
}

function call_home_rsa_setup()
{
	rsa="$HOME/workspace/.system/call_home_rsa"
	if [ ! -f "$rsa" ]
	then
	    ssh-keygen -t rsa -f $rsa -N "" -C call-home-rsa -q
	fi
	authorized_keys="$HOME/.ssh/authorized_keys"
	if [ -f "$authorized_keys" ]
	then
		sed -e "s/.* call-home-rsa//" $authorized_keys > $authorized_keys-tmp
		mv $authorized_keys-tmp $authorized_keys
	fi
	cat $rsa.pub >> $authorized_keys
	whoami > $HOME/workspace/.system/mac-user
	ip="$(ifconfig en0 | grep inet | grep -v inet6)"
	if [ "$ip" == "" ]
	then
		ip="$(ifconfig en1 | grep inet | grep -v inet6)"
	fi
	echo "$ip" | awk '{print $2}' > $HOME/workspace/.system/mac-ip
}

function increase_disk_size()
{
	disk_size_file="$HOME/workspace/.system/$1-disk-size"
	cd $WORKSPACE
	vagrant halt $1
	vmware_fusion="/Applications/VMware Fusion.app"
	if [ -d "$HOME$vmware_fusion" ]
	then
		vmware_fusion="$HOME$vmware_fusion"
	fi

	if [ ! $2 ]
	then
		echo "Missing argument: size"
		exit
	fi
	echo "increasing size of $1: ${2}GB"
	"$vmware_fusion/Contents/Library/vmware-vdiskmanager" -x "${2}GB" "$WORKSPACE/.vagrant/machines/$1/vmware_fusion/"*/*.vmdk && echo $2 > $disk_size_file
	vagrant up $1
}

function check_disk_size()
{
	disk_size_file="$HOME/workspace/.system/$1-disk-size"
	size="$(get_json "$env" 'disk')"
	if [ ! $size ]
	then
		size="20"
	fi
	if [ -f $disk_size_file ]
	then
		if [ "$(cat $disk_size_file)" != "$size" ]
		then
			increase_disk_size $1 $size
		fi
	else
		increase_disk_size $1 $size
	fi
}

if [ $FUNCTION ]
then
	$FUNCTION $@
	exit
fi

INSTANCE="$1"

if [ "$(which vagrant)" == "" ]
then
	error "Vagrant could not be found."
	exit
fi

env="$(cat "$WORKSPACE/env.json")"
function get_json()
{
    echo $1 | sed -e 's/^[{}]*//g' | awk -F=':' -v RS=',' "\$1~/\"$2\"/ {print}" | sed -e "s/\"$2\"://" | tr -d "\n\t" | sed -e 's/\\"/"/g' | sed -e 's/\\\\/\\/g' | sed -e 's/^[ \t]*//g' | sed -e 's/^"//'  -e 's/"$//'
}

provider="$(get_json "$env" 'provider')"
export VAGRANT_DEFAULT_PROVIDER="${provider//-/_}"
if [ "$VAGRANT_HOME" == "" ]
then
	vagrant_home="$WORKSPACE/.vagrant.d"
	if [ ! -d "$HOME/.vagrant.d" ] && [ ! -d "$vagrant_home" ]
	then
		mkdir "$vagrant_home"
	fi
	if [ ! -d "$vagrant_home" ]
	then
		vagrant_home="$HOME/.vagrant.d"
	fi
	export VAGRANT_HOME="$vagrant_home"
fi

while [ "$(cat "$WORKSPACE/config/git.json")" == "$(cat "$WORKSPACE/workspace-image/config-boilerplate/git.json")" ]
do
	info "Please enter the path to your Git config file or edit ${WORKSPACE/$HOME/~}/config/git.json manually and hit [enter]."
    read git_config_file
    if [ "$git_config_file" != "" ]
	then
		if [ "${git_config_file:$(expr ${#git_config_file} - 5):5}" != '.json' ]
		then
			git_config_file="$git_config_file/git.json"
		fi
		
		scp "$git_config_file" "$WORKSPACE/config/git.json"

		if [ "$(cat "$WORKSPACE/config/git.json")" == "$(cat "$WORKSPACE/workspace-image/config-boilerplate/git.json")" ]
		then
			warning "No Git config file found."
		else
			success "Git config file found!"
		fi
	elif [ "$(cat "$WORKSPACE/config/git.json")" == "$(cat "$WORKSPACE/workspace-image/config-boilerplate/git.json")" ]
	then
		warning "No changes detected in git.json"
	fi
done

if [ "$provider" == "vmware-fusion" ] && [ ! -f "$VAGRANT_HOME/license-vagrant-vmware-fusion.lic" ]
then
	while [ ! -f "$WORKSPACE/config/"*.lic ]
	do
		info "Please enter the path to your Vagrant VMWare Fusion License file or place it manually in your ${WORKSPACE/$HOME/~}/config directory and hit [enter]."
		read vagrant_vmware_fusion_license
		if [ "$vagrant_vmware_fusion_license" == "" ]
		then
			exit
		fi
		
		if [ "${vagrant_vmware_fusion_license:$(expr ${#vagrant_vmware_fusion_license} - 4):4}" != '.lic' ]
		then
			vagrant_vmware_fusion_license="$vagrant_vmware_fusion_license/"*.lic
		fi
		
		scp "$vagrant_vmware_fusion_license" "$WORKSPACE/config/"

		if [ ! -f "$WORKSPACE/config/"*.lic ]
		then
			warning "No license file found."
		fi
	done
	success "License file found!"
	vagrant plugin install vagrant-vmware-fusion || exit
	vagrant plugin install vagrant-triggers
	vagrant plugin license vagrant-vmware-fusion "$(ls "$WORKSPACE/config/"*.lic | head -1)"

	# Check if VMWare has ran a first time before
	if [ ! -d "$HOME/Library/Application Support/VMWare Fusion" ]
	then
		if [ -d "$HOME/Applications/VMWare Fusion.app" ]
		then
			vmware_app="$HOME/Applications/VMWare Fusion.app"
		elif [ -d "/Applications/VMWare Fusion.app" ]
		then
			vmware_app="/Applications/VMWare Fusion.app"
		else
			error "There was no VMWare Fusion.app found on your system"
			error "Install VirtualBox or VMWare Fusion first"
			exit
		fi
		
		open "$vmware_app"
		info "Please run 'workspace' again if the VMWare Fusion is activated"
		exit
	fi
elif [ "$provider" == "virtualbox" ] && [ -f "$WORKSPACE/.system/"*.vbox-extpack ]
then
	if [ ! -f "$WORKSPACE/.system/extpack-installed" ]
	then
		open "$WORKSPACE/.system/"*.vbox-extpack
		info "Please run 'workspace' again if the Extension Pack has been installed"
		touch "$WORKSPACE/.system/extpack-installed"
		exit
	else
		rm -f "$WORKSPACE/.system/"*.vbox-extpack
		rm -f "$WORKSPACE/.system/extpack-installed"
	fi
fi

if [ $STATUS ]
then
	vagrant global-status
	exit
fi

if [ ! "$INSTANCE" ]
then
	INSTANCE=1
fi

INSTANCE="$(printf "%0*d\n" 2 ${INSTANCE:-1})"

running_file="$WORKSPACE/.system/coreos-$INSTANCE-running"

if [ $REBUILD ] || [ $DESTROY ]
then
	info "Destroying coreos-$INSTANCE..."
	vagrant destroy $DEBUG --force "coreos-$INSTANCE" 2>/dev/null
	if [ -f "$running_file" ]
	then
		rm "$running_file"
	fi
	if [ $DESTROY ]
	then
		vagrant global-status $DEBUG
		exit
	fi
fi

function vagrant_ssh()
{
	check_disk_size coreos-$INSTANCE
	if [ "${COMMAND:0:9}" == "workspace" ]
	then
		info "Logging into workspace on coreos-$INSTANCE..."
		vagrant ssh $DEBUG --command "$COMMAND" "coreos-$INSTANCE"
	elif [ "$COMMAND" != "" ]
	then
		info "Running your command on coreos-$INSTANCE..."
		vagrant ssh $DEBUG --command "$COMMAND" "coreos-$INSTANCE"
	else
		info "Logging into coreos-$INSTANCE..."
		vagrant ssh $DEBUG "coreos-$INSTANCE"
	fi
}

if [ ! $RELOAD ] && [ -f "$running_file" ]
then
	call_home_rsa_setup
	vagrant_ssh
	info "checking status... "
	status="$(vagrant status coreos-$INSTANCE 2>/dev/null)"
	if [ "${status/not running/}" != "$status" ]
	then
		rm "$running_file"
		if [ $COMMAND ]
		then
			./coreos -c "$COMMAND"
		else
			./coreos
		fi
	fi
	exit
fi

info "Looking for status coreos-$INSTANCE..."
status="$(vagrant status coreos-$INSTANCE 2>/dev/null)"
if [ "${status/not running/}" != "$status" ]
then
	info "Resuming coreos-$INSTANCE..."
	vagrant up $DEBUG "coreos-$INSTANCE"
elif [ "${status/not created/}" != "$status" ]
then
	info "Creating coreos-$INSTANCE..."
	vagrant up $DEBUG "coreos-$INSTANCE"
else
	if [ "$INSTANCE" == "01" ] && [ "$(vagrant ssh --command "ls -A /workspace" "coreos-$INSTANCE")" == "" ]
	then
		RELOAD=1
	fi
	if [ $RELOAD ]
	then
		info "Reloading coreos-$INSTANCE"
		if [ $PROVISION ]
		then
			vagrant reload $DEBUG "coreos-$INSTANCE"
		else
			vagrant reload $DEBUG --provision "coreos-$INSTANCE"
		fi
	else
		info "Already running coreos-$INSTANCE"
		if [ $PROVISION ]
		then
			info "Provisioning coreos-$INSTANCE..."
			vagrant provision $DEBUG "coreos-$INSTANCE"
		fi
	fi
fi

status="$(vagrant status coreos-$INSTANCE 2>/dev/null)"
if [ "${status/not running/}" == "$status" ]
then
	touch "$running_file"
	vagrant_ssh
fi