#!/usr/bin/env python
import os
import sys

sys.path.append(os.environ.get('WORKSPACE', os.environ.get('HOME')+'/workspace')+'/.python-packages')

from workspace import cli

if __name__ == '__main__':
    cli()
