#!/bin/bash
function get_json()
{
    echo $1 | sed -e 's/^[{}]*//g' | awk -F=':' -v RS=',' "\$1~/\"$2\"/ {print}" | sed -e "s/\"$2\"://" | tr -d "\n\t" | sed -e 's/\\"/"/g' | sed -e 's/\\\\/\\/g' | sed -e 's/^[ \t]*//g' | sed -e 's/^"//'  -e 's/"$//'
}

author="$(cat "$CONFIG_DIR/author.json")"
export AUTHOR_NAME="$(get_json $author author_name)"
export AUTHOR_EMAIL="$(get_json $author author_email)"
unset author

function docker_login()
{
	docker="$(cat "$CONFIG_DIR/docker.json")"
	docker login \
		--email="$(get_json $docker email)" \
		--username="$(get_json $docker username)" \
		--password="$(get_json $docker password)" \
		"$(get_json $docker host)"
	unset docker
}

alias art="php artisan"

export ENVIRONMENT="dev"
export PATH="$HOME/bin:/usr/local/bin:$PATH"
export PATH="$PATH:$HOME/.rvm/bin"
export PATH="/usr/local/node/bin:$PATH"
export PATH="$PATH:$HOME/.local/bin"
export PATH="$CONFIG_DIR/bin:/workspace/bin-workspace:$PATH"
export PATH="$PATH:/workspace/bin-coreos"
export PATH="./vendor/bin:$PATH"
export DIGITALOCEAN_CRANE_TOKEN=""

source ~/.rvm/scripts/rvm
rvm --quiet-curl --install --default use $(rvm list strings) 2>/dev/null

sudo chmod +x /workspace/bin-workspace/*
sudo chmod +x /workspace/bin-coreos/*
sudo chmod +x $CONFIG_DIR/bin/*