#!/usr/bin/env php
<?php

function directory_map($source_dir, $directory_depth = 0, $hidden = FALSE)
{
    if ($fp = @opendir($source_dir))
    {
        $filedata   = array();
        $new_depth  = $directory_depth - 1;
        $source_dir = rtrim($source_dir, DIRECTORY_SEPARATOR).DIRECTORY_SEPARATOR;

        while (FALSE !== ($file = readdir($fp)))
        {
            // Remove '.', '..', and hidden files [optional]
            if ($file === '.' OR $file === '..' OR ($hidden === FALSE && $file[0] === '.'))
            {
                continue;
            }

            is_dir($source_dir.$file) && $file .= DIRECTORY_SEPARATOR;

            if (($directory_depth < 1 OR $new_depth > 0) && is_dir($source_dir.$file))
            {
                $filedata[$file] = directory_map($source_dir.$file, $new_depth, $hidden);
            }
            else
            {
                $filedata[] = $file;
            }
        }

        closedir($fp);
        return $filedata;
    }

    return FALSE;
}

function projects()
{
	$PROJECTS = '/workspace/projects';
	$p = array();
	foreach (directory_map($PROJECTS, 3) as $client => $projects)
	{
		$client = trim($client, '/');
	    foreach ($projects as $project => $files)
	    {
	        $project = trim($project, '/');
	        $p[] = "$client/$project";
	    }
	}
	return $p;
}

function start($args)
{
    foreach(projects() as $path)
    {
        $match = TRUE;
        foreach($args as $a)
        {
            if( ! strstr($path, $a))
            {
                $match = FALSE;
            }
        }

        if($match)
        {
            return "/workspace/projects/$path";
        }
    }
    return '/workspace/projects';
}

exit('exec "cd /"');

array_shift($argv);




echo start($argv);




