#!/usr/bin/php
<?php

$terraform = '/workspace/terraform/terraform.tfstate';
$state = json_decode(file_get_contents($terraform), TRUE);

$command = [
	'docker run',
	'-d',
	'-p 5000:5000',
	'-e STORAGE_PATH=/registry',
	'-v $HOME/share/registry:/registry',
	'registry',
];



exec("ssh crobays@")
