#!/bin/bash

cd /workspace/projects

get crobays/haproxy-ubuntu
#get crobays/gulp
get crobays/nginx-php
get crobays/nginx-php-centos6
get crobays/nginx-php-centos7
get crobays/mysql

fig kill
fig rm --force
fig up
