export PATH="$HOME/bin-`uname -s | tr '[:upper:]' '[:lower:]'`:$HOME/workspace/bin:$PATH"
export WORKSPACE_HOST_NAME="default"

if [ "$HOSTNAME" != "workspace" ];then
    export WORKSPACE="$HOME/workspace"
    source $WORKSPACE/home/zsh-custom/zshrc-local
    export PATH="$HOME/bin:$HOME/.bin:$PATH"
    alias ws="$WORKSPACE/bin/workspace ssh"
    export ZSH="$WORKSPACE/.oh-my-zsh"
else
    # build-time 2>/dev/null || echo -n ''
    alias ws="exit"
    source /etc/zsh/zshenv
fi

source $WORKSPACE/.zsh/zshrc-oh-my-zsh
source $WORKSPACE/.zsh/zshrc-extra
export ZSH_CUSTOM=${ZSH_CUSTOM:-$WORKSPACE/home/zsh-custom}
source $ZSH_CUSTOM/zshrc-oh-my-zsh
source $ZSH_CUSTOM/zshrc-extra
[ -e $ZSH_CUSTOM/zshrc-local ] || touch $ZSH_CUSTOM/zshrc-local
source $ZSH_CUSTOM/zshrc-local
source $ZSH_CUSTOM/zshrc-keybindings

if [ "$HOSTNAME" != "workspace" ];then
    export PATH="$WORKSPACE/bin:$PATH"
    workspace ssh
fi
