#!/bin/bash
 
remove_dangling() {
   echo "Removing dangling images ..."
   docker rmi $(docker images --filter dangling=true -q)
}
 
remove_stopped_containers() {
    echo "Removing stopped containers ..."
    docker rm --volumes $(docker ps -qa)
}

help() {
    echo "usage: docker-clean containers|images"                                                                                                                                             
    echo "  containers    removes all stopped containers it can."
    echo "  images        removes dangling (un-needed) image layers - images you no longer need"
}

cmd=${1}
shift
case $cmd in
    images)
        remove_dangling
        ;;
    containers)
        remove_stopped_containers
        ;;
    *)
        help
        ;;
esac
