#!/bin/bash
 
remove_dangling() {
   echo "Removing dangling images ..."
   docker rmi $(docker images --filter dangling=true -q)
}
 
remove_stopped_containers() {
    echo "Removing stopped containers ..."
    docker rm $(docker ps -qa)
}
 
case $1 in
    images)
        remove_dangling
        ;;
    containers)
        remove_stopped_containers
        ;;
    *)
        echo "                                                                                                                                                                       
usage: docker-clean containers|images                                                                                                                                                
    containers - removes all stopped containers it can.                                                                                                                              
    images - removes dangling (un-needed) image layers - images you no longer need                                                                                                   
    data - removes data (/var/lib/docker/overlay)                                                                                                   
"
        ;;
esac