#!/bin/bash
path_or_url="${@:-./}"
path="$(readlink -f $path_or_url)"
if [ $path ]
then
	path_or_url="$path"
	path_or_url="${path_or_url/\/workspace/\~/workspace}"
	echo $path_or_url
fi
ssh-home-command "open \"$path_or_url\""