#!/bin/bash
usage()
{
cat << EOF

usage: $(basename $0) options WORKSPACE-NUM

This script handles your Workspace instances with Docker (docker.com)

OPTIONS:
    -h (help)           Show this message
    -t (tag)            The base version of the base (default to \'latest\')
    -r (recreate)       Recreate workspace
    -R [tag] (rebuild)  Rebuild workspace image from Dockerfile with new tag
    -c (cache)          Use cache when building base image
    -d (destroy)        Kill and destroy workspace container
    -l (log level)      Log level 1: Actions 2: with execs and curls
    -C (command)        Execute a command in workspace
EOF
}
BASE_NAME="workspace"
LOG_LEVEL="0"
count=0
while getopts “ht:rR:cdl:C:” OPTION
do
         case $OPTION in
            h)
                usage
                exit 1
                ;;
            t)
                IMAGE_TAG="$OPTARG"
                ;;
            r)
                RERUN_CONTAINER=1
                ;;
            R)
                REBUILD_IMAGE_TAG="$OPTARG"
                ;;
            c)
                USE_CACHE=1
                ;;
            d)
                DESTROY=1
                ;;
            l)
                LOG_LEVEL="$OPTARG"
                ;;
            C)
                COMMAND="$OPTARG"
                ;;
            ?)
                usage
                exit
                ;;
         esac
        count=`expr $count + 1`
        if [ "$OPTARG" ]
        then
            count=`expr $count + 1`
        fi
done
shift $count

black="\e[0;30m"
red="\e[0;31m"
green="\e[0;32m"
orange="\e[0;33m"
blue="\e[0;34m"
purple="\e[0;35m"
turquase="\e[0;36m"
NC="\e[0m"

function info ()
{
    printf "$turquase"
    echo "$1"
    printf "$NC"
}

function success ()
{
    printf "$green"
    echo "$1"
    printf "$NC"
}

function warning ()
{
    printf "$orange"
    echo "$1"
    printf "$NC"
}

function error ()
{
    printf "$red"
    echo "$1"
    printf "$NC"
}

env="$(cat '/workspace/env.json')"
function get_json()
{
    echo $1 | sed -e 's/^[{}]*//g' | awk -F=':' -v RS=',' "\$1~/\"$2\"/ {print}" | sed -e "s/\"$2\"://" | tr -d "\n\t" | sed -e 's/\\"/"/g' | sed -e 's/\\\\/\\/g' | sed -e 's/^[ \t]*//g' | sed -e 's/^"//'  -e 's/"$//'
}

function log()
{
    if [ "$LOG_LEVEL" == "1" ]
    then
        echo $1
    fi
}

if [ "$IMAGE_TAG" == "" ]
then
    IMAGE_TAG="latest"
fi

image_tag_username="crobays"
git_config_file="/workspace/config/git.json"
if [ ! -d /workspace/workspace-image ]
then
    pull_image=1
else
    if [ -f "/workspace/.system/workspace-image-tag-username" ]
    then
        image_tag_username="$(cat /workspace/.system/workspace-image-tag-username)"
    fi

    workspace_base_dir="/workspace/workspace-image"
    if [ "$(cat $git_config_file)" == "$(cat "$workspace_base_dir/config-boilerplate/git.json")" ]
    then
        warning "First set your Git credentials in ./config/git.json"
        exit
    fi
fi

workspace_base_image="$image_tag_username/workspace"
workspace_archive_dir="/workspace/.docker-images"
workspace_image_latest_file="$workspace_archive_dir/$image_tag_username-SLASH-workspace-COLON-latest.tar"
workspace_image_file="$workspace_archive_dir/$image_tag_username-SLASH-workspace-COLON-$IMAGE_TAG.tar"
workspace_rebuild_image_file="$workspace_archive_dir/$image_tag_username-SLASH-workspace-COLON-$REBUILD_IMAGE_TAG.tar"
NAME="$BASE_NAME-$(printf "%0*d\n" 2 ${1:-1})"

workspace_status_file="/workspace/.system/workspace-status"
if [ -f "$workspace_status_file" ]
then
    status="$(cat $workspace_status_file)"
    echo "Your workspace image is $status in another process. Please retry when ready."
    exit
fi

if [ ! $REBUILD_IMAGE_TAG ] && [ "$(docker inspect $workspace_base_image:$IMAGE_TAG 2>/dev/null)" == "[]" ]
then
    if [ -f "$workspace_image_file" ]
    then
        info "Loading $workspace_base_image:$IMAGE_TAG from $workspace_image_file"
        echo "loading" > "$workspace_status_file"
        docker load --input "$workspace_image_file"
        rm "$workspace_status_file"
        if [ "$IMAGE_TAG" != "latest" ]
        then
            docker tag "$workspace_base_image:$IMAGE_TAG" "$workspace_base_image:latest"
        fi
    else
        pull_image=1
    fi
fi

if [ $REBUILD_IMAGE_TAG ] || [ "$(docker inspect $workspace_base_image:$IMAGE_TAG 2>/dev/null)" == "[]" ]
then
    if [ ! $REBUILD_IMAGE_TAG ]
    then
        REBUILD_IMAGE_TAG="$IMAGE_TAG"
    fi

    if [ $pull_image ]
    then
        echo "pulling" > "$workspace_status_file"
        docker pull "$workspace_base_image:$REBUILD_IMAGE_TAG"
        rm "$workspace_status_file"
    else
        no_cache="--no-cache"
        if [ $USE_CACHE ]
        then
            no_cache="$no_cache=false"
        else
            no_cache="$no_cache=true"
            start_date="$(date)"
        fi
        username="$(get_json "$env" 'username')"
        if [ "$username" != "$image_tag_username" ]
        then
            echo "$username" > /workspace/.system/workspace-image-tag-username
        fi
        echo "building" > "$workspace_status_file"
        docker build \
            --tag "$workspace_base_image:$REBUILD_IMAGE_TAG" \
            $no_cache \
            "$workspace_base_dir"
        rm "$workspace_status_file"
    fi

    if [ "$(docker inspect $workspace_base_image:$REBUILD_IMAGE_TAG 2>/dev/null)" != "[]" ]
    then
        if [ "$start_date" != "" ]
        then
            echo "Started: $start_date"
            echo "Ended:   $(date)"
        fi

        if [ "$REBUILD_IMAGE_TAG" != "latest" ]
        then
            docker tag -f "$workspace_base_image:$REBUILD_IMAGE_TAG" "$workspace_base_image:latest"
        fi

        if [ -f "$workspace_image_file" ]
        then
            rm -f "$workspace_image_file"
        fi
        info "Saving $workspace_base_image:$REBUILD_IMAGE_TAG to $workspace_rebuild_image_file"
        echo "saving" > "$workspace_status_file"
        docker save --output "$workspace_rebuild_image_file" "$workspace_base_image:$REBUILD_IMAGE_TAG"
        rm "$workspace_status_file"
        if [ "$REBUILD_IMAGE_TAG" != "latest" ]
        then
            if [ -f "$workspace_image_latest_file" ]
            then
                rm -f "$workspace_image_latest_file"
            fi
            echo "saving" > "$workspace_status_file"
            docker save --output "$workspace_image_latest_file" "$workspace_base_image:latest"
            rm "$workspace_status_file"
        fi
    else
        error "Sorry to say... but building $workspace_base_image:$REBUILD_IMAGE_TAG failed"
        exit
    fi
    IMAGE_TAG="$REBUILD_IMAGE_TAG"
    RERUN_CONTAINER=1
fi

if [ $DESTROY ]
then
    docker rm -f "$NAME" 2>/dev/null
    exit
fi

git_config_lock_file="/workspace/.system/git.json.lock"
if [ ! $RERUN_CONTAINER ] && [ -f "$git_config_lock_file" ] && [ "$(cat $git_config_lock_file)" != "$(cat $git_config_file)" ]
then
    RERUN_CONTAINER=1
fi

if [ $RERUN_CONTAINER ]
then
    docker rm -f "$NAME" 2>/dev/null
fi

container_state_running="$(docker inspect --format='{{.State.Running}}' "$NAME" 2>/dev/null)"

if [ "$container_state_running" == "" ]
then
    log "docker run"
    docker run \
        --name "$NAME" \
        --hostname "$HOSTNAME-$NAME" \
        --volume "/workspace:/workspace" \
        --volume "/var/run/docker.sock:/var/run/docker.sock" \
        --env "CONFIG_DIR=/workspace/config" \
        --env "SYSTEM_DIR=/workspace/.system" \
        --env "LOG_LEVEL=$LOG_LEVEL" \
        --env "DOCKER_NAME=$NAME" \
        --env "TIMEZONE=$(get_json "$env" 'timezone')" \
        --env "USERNAME=$(get_json "$env" 'username')" \
        --interactive \
        --tty \
        "$workspace_base_image:$IMAGE_TAG" \
        $COMMAND
elif [ "$container_state_running" == "false" ]
then
    log "docker start"
    docker start \
        --interactive \
        "$NAME"
elif [ "$container_state_running" == "true" ]
then
    log "docker exec"
    if [ ! $COMMAND ]
    then
        COMMAND="$(docker inspect --format='{{(index .Config.Entrypoint 0)}}' "$NAME")"
    fi
    docker exec \
        --interactive \
        --tty \
        "$NAME" \
        $COMMAND
fi
